### ISSUE TITLE
how we use this module?

### ISSUE THREAD

**Issue by rrafik** [straga/odoo_vik_main#1]
Hi,
please, how we can call the message function?

**Comment by straga** [comment]
what module ?

**Comment by rrafik** [comment]
excuse me...
popup_message

**Comment by straga** [comment]
self.pool.get('popup.message').info(cr, uid, title='Check Connection', message="My message here"))

**Comment by rrafik** [comment]
Thank you for the information and for the module too

**Comment by straga** [comment]
Ok
